### ISSUE TITLE
Error when attempting to run image.

### ISSUE THREAD

**Issue by tariqk** [tariqk/dwarf-fortress-lnp-docker#1]
Error message occurs when attempting to run `./start-df-lnp-docker`, after successfully completing `make`:

```
Failed to get capabilities of file `LNP/utilities/dwarf_therapist/DwarfTherapist' (Operation not supported)
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.lnp", line 48, in __init__
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.errorlog", line 70, in start
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.errorlog", line 65, in redirect
IOError: [Errno 13] Permission denied: './../../../../../stdout.txt'
```

**Comment by tariqk** [comment]
Result of `ls -al` in `~/bin/df`:

```
total 9448
drwxr-xr-x  6 Urist Urist    4096 Oct 23 17:23 .
drwxr-xr-x  7 Urist Urist    4096 Oct 23 17:23 ..
drwx------ 16 Urist Urist    4096 Oct 23 17:23 df_linux
-rw-rw-r--  1 Urist Urist     457 Mar 22  2015 dflogo128.png
drwxrwxr-x 18 Urist Urist    4096 Oct 23 17:23 LNP
-rwxr-xr-x  1 Urist Urist 9605854 Mar  3  2015 PyLNP
-rw-rw-r--  1 Urist Urist     972 Mar 22  2015 PyLNP.json
-rw-r--r--  1 Urist Urist      82 Oct 23 16:42 PyLNP.user
-rw-rw-r--  1 Urist Urist   14742 Mar 15  2015 README.md
-rwxr-xr-x  1 Urist Urist     502 Mar 22  2015 startlnp
-rwxr-xr-x  1 Urist Urist   13117 Mar  3  2015 xdg-terminal
```

Results of `ls -al` in `~/bin/df/df_linux`:

```
ls: cannot access stonesense: Permission denied
ls: cannot access data: Permission denied
ls: cannot access g_src: Permission denied
ls: cannot access hack: Permission denied
ls: cannot access sdl: Permission denied
ls: cannot access libs: Permission denied
ls: cannot access raw: Permission denied
total 300
drwx------ 16 Urist Urist   4096 Oct 23 17:23 .
drwxr-xr-x  6 Urist Urist   4096 Oct 23 17:23 ..
-rwxr-xr-x  1 Urist Urist    956 Feb 28  2015 command line.txt
d?????????  ? ?     ?          ?            ? data
-rwxr-xr-x  1 Urist Urist    493 Mar 22  2015 df
-rwxr-xr-x  1 Urist Urist   2591 Mar 22  2015 dfhack
-rw-rw-r--  1 Urist Urist   7515 Mar 22  2015 dfhack.init
-rw-rw-r--  1 Urist Urist   7016 Mar 15  2015 dfhack.init-example
-rwxr-xr-x  1 Urist Urist    140 Mar 22  2015 dfhack-run
-rwxr-xr-x  1 Urist Urist   3526 Mar 22  2015 distro_fixes.sh
-rwxr-xr-x  1 Urist Urist  74033 Feb 28  2015 file changes.txt
-rw-rw-r--  1 Urist Urist     52 Feb 28  2015 gamelog.txt
d?????????  ? ?     ?          ?            ? g_src
d?????????  ? ?     ?          ?            ? hack
d?????????  ? ?     ?          ?            ? libs
d?????????  ? ?     ?          ?            ? raw
-rwxr-xr-x  1 Urist Urist   1364 Feb 28  2015 README.linux
-rwxr-xr-x  1 Urist Urist  11025 Feb 28  2015 readme.txt
-rwxr-xr-x  1 Urist Urist 153290 Feb 28  2015 release notes.txt
d?????????  ? ?     ?          ?            ? sdl
-rw-rw-r--  1 Urist Urist   4626 Feb 28  2015 stderr.log
-rw-rw-r--  1 Urist Urist      0 Feb 28  2015 stdout.log
d?????????  ? ?     ?          ?            ? stonesense
```

With `sudo`:

```
total 328
drwx------ 16 Urist Urist   4096 Oct 23 17:23 .
drwxr-xr-x  6 Urist Urist   4096 Oct 23 17:23 ..
-rwxr-xr-x  1 Urist Urist    956 Feb 28  2015 command line.txt
drwx------ 18 Urist Urist   4096 Oct 23 17:23 data
-rwxr-xr-x  1 Urist Urist    493 Mar 22  2015 df
-rwxr-xr-x  1 Urist Urist   2591 Mar 22  2015 dfhack
-rw-rw-r--  1 Urist Urist   7515 Mar 22  2015 dfhack.init
-rw-rw-r--  1 Urist Urist   7016 Mar 15  2015 dfhack.init-example
-rwxr-xr-x  1 Urist Urist    140 Mar 22  2015 dfhack-run
-rwxr-xr-x  1 Urist Urist   3526 Mar 22  2015 distro_fixes.sh
-rwxr-xr-x  1 Urist Urist  74033 Feb 28  2015 file changes.txt
-rw-rw-r--  1 Urist Urist     52 Feb 28  2015 gamelog.txt
drwx------  2 Urist Urist   4096 Oct 23 17:23 g_src
drwx------ 18 Urist Urist   4096 Oct 23 17:23 hack
drwx------  2 Urist Urist   4096 Oct 23 17:23 libs
drwx------  8 Urist Urist   4096 Oct 23 17:23 raw
-rwxr-xr-x  1 Urist Urist   1364 Feb 28  2015 README.linux
-rwxr-xr-x  1 Urist Urist  11025 Feb 28  2015 readme.txt
-rwxr-xr-x  1 Urist Urist 153290 Feb 28  2015 release notes.txt
drwx------  2 Urist Urist   4096 Oct 23 17:23 sdl
-rw-rw-r--  1 Urist Urist   4626 Feb 28  2015 stderr.log
-rw-rw-r--  1 Urist Urist      0 Feb 28  2015 stdout.log
drwx------ 22 Urist Urist   4096 Oct 23 17:23 stonesense
```

The directories in `df_linux` are set wrong: they're set to `700` when it should be something more like `755`. Might be something up with the LNP zip file itself.

Proposed workaround would be to include `find . -type d -exec chmod +rx {} \;` in the Dockerfile build steps, after unzipping the archives, if we're just going to do the directories. Or just straight up use `chmod -R +rx /home/Urist/bin/df`.

**Comment by tariqk** [comment]
Result of `unzip -Z resources/install.zip | grep rwx------`:

```
drwx------  6.3 unx        0 bx stor 15-Mar-29 18:58 04024r3-x64/df_linux/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/announcement/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/art/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/dipscript/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/dipscript/text/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/help/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/init/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/initial_movies/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/sound/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/data/speech/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/g_src/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/images/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/include/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/include/df/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/include/df/custom/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/include/modules/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/libs/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/libs/pkgconfig/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/lua/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/lua/dfhack/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/lua/gui/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/lua/plugins/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/lua/plugins/dfusion/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/lua/plugins/sort/
drwx------  6.3 unx        0 bx stor 15-Mar-29 18:59 04024r3-x64/df_linux/hack/plugins/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/raw/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/ruby/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/scripts/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/scripts/devel/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/scripts/fix/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/scripts/gui/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/hack/scripts/modtools/
drwx------  6.3 unx        0 bx stor 15-Mar-15 20:33 04024r3-x64/df_linux/libs/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/graphics/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/graphics/doren/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/graphics/jiripetru/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/graphics/kafine/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/graphics/magnut/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/graphics/nwkohaku/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/graphics/phoebus/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/graphics/sphr/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/interaction examples/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/objects/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/objects/notes/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/raw/objects/text/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/sdl/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/Fluids/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/buildings/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/buildings/include/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/colors/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/creatures/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/creatures/large_128/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/creatures/large_256/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/creatures/large_64/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/grasses/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/growths/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/items/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/items/greiger items/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/phoebus/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/phoebus/doren/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/phoebus/jiripetru/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/phoebus/kafine/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/phoebus/magnut/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/phoebus/nwkohaku/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/phoebus/phoebus/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/phoebus/sphr/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/terrain/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/terrain/DF_2014_Trees/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/terrain/DarkTundra/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/vegetation/
drwx------  6.3 unx        0 bx stor 15-Mar-01 00:18 04024r3-x64/df_linux/stonesense/vegetation/DT_trees/
```

So that's the source of the problem. The wonky permissions come from the ZIP files themselves.
